### ISSUE TITLE
Filters and pagination in search service

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/eosc-search-service#116]
- [ ] ~~specification for the final version of filters in each type of product~~
- [ ] ~~filter per category - specification~~
- [ ] ~~adding new types of filters (data, Yes/no)~~

---
- #123
- #124
- #125 
- #103
