### ISSUE TITLE
Write detailed deployment procedures for our services

### ISSUE THREAD

**Issue by Michal-Kolomanski** [cyfronet-fid/eosc-search-service#1238]
We have a good starting point. Recently we wrote deployment procedures for general documentation purposes.
Now we should write detailed deployment procedures for our purposes, including information e.g. where a specific instance is, authorization, some specific commands for our environment etc.

- [ ] As a developer I can know where each specific instance of certain service is (prod/beta) - on which machine, how to get there etc.
- [ ] As a developer I can deploy beta SS, Transfomer, MP if needed
- [ ] As a developer I can check if certain PR has been rebuilt
- [ ] As a developer I can rebuilt certain PR (maybe with some specific .env?)
- [ ] Discussion about who should be able to deploy beta etc. when Wojt is not avaiable. Establish rules
