### ISSUE TITLE
Finish dump upload endpoint

### ISSUE THREAD

**Issue by Michal-Kolomanski** [cyfronet-fid/eosc-search-service#1321]
Based on the provided skeleton do:
- [ ] validate
- [x] *optional solr collection creation
- [ ] load data from a cloud (S3 bucket)
- [ ] transform & send to solr/s3
- [ ] make a full update of peripheral data into solr/s3

**Comment by Michal-Kolomanski** [comment]
load data: https://github.com/cyfronet-fid/eosc-search-service/issues/1401

**Comment by wiktorflorian** [comment]
read & transform:  #1434 
send: #1435
