### ISSUE TITLE
Make Sandbox a pre-prod environment

### ISSUE THREAD

**Issue by Michal-Kolomanski** [cyfronet-fid/eosc-search-service#1477]
Scope:
- [x] use prod solr 
- [x] use prod JMS `https://integration.providers.sandbox.eosc-beyond.eu/`
- [x] build proper commons for sandbox services 
- [ ] etc. if needed
