### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/eosc-search-service#159]
- [x] separate layouts (UI)
  - [x] results & pagination
  - [x] collections navigation
  - [x] search bar
  - [x] filters (1 day)
  - [x] active filters (1 day)
  - [x] page header
  - [x] main header (auth)
  - [x] restore all collections with new interfaces
  - [x] add all collections config pointing to publications (for now)
  - [ ] ~~environment variables should be injected as static data instead of direct import~~
  - [x] add components alias and refactor all places
  - [x] add collections alias and refactor all places
  - [x] use query mutator before fetching results
  - [x] restore training page and its routing (0.5 day)
  - [x] check & fix all found bugs (1 - 2 days)
  - [x] turn on noImplicitAny and fix errors
  - [x] rebase to new changes of @jarekzet (1 day)
- [x] add configs validators (2 - 3 days)
  - [x] check collection name consistency
  - [x] check label name consistency
  - [x] check metadata facets and filters consistency
- [ ] Unit Tests (OPTIONAL, when free time availbale)

Max: 6.5 days

### Additional
- [x] Add error page
- [x] Separate pages
- [x] merge all libs into search-page
- [x] split the search page into smaller components
- [x] separate utils
- [x] separate types
