### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/eosc-search-service#178]
### Features
- [x] redirect to URL 
- [x] extend an adapter with
   - [x] tags (with background), color depends on data type (for example open access everywhere is green)
   - [x] labels (yellow one)
   - [x] add date field
- [ ] Add possibility to choose filter type from collection/set level and add new filter types #123  - [ ] remove the router from the custom router
  - [x] fat arrow functions to standard functions
  - [x] change the custom router to a custom route
  - [x] provide serializers for each filter type
  - [x] add validation for filters types & serializers
  - [x] Cleaning data (BLOCKED) #164
  - [x] add dates ranges & its serializer
        https://stackoverflow.com/questions/8678867/how-to-write-a-solr-query-for-retrieving-all-records-with-numeric-field-value-le
  - [ ] add range (like video time) & its serializer
        https://stackoverflow.com/questions/8678867/how-to-write-a-solr-query-for-retrieving-all-records-with-numeric-field-value-le
  - [ ] add select (open access -> yes, no) & its serializer
- [ ] recommendations (like in marketplace)

### Bugs
- [x] Clear all filter does not clear the entered phrase #173
- [ ] Unselected filter no longer exists #172
- [ ] Improve the behavior of search bar #176
  - [ ] Autocomplete list does not disappear after clicking the "enter" button or the "search" button #174
- [ ] Scientific Domain and Categories from Home Page should redirect to Services #167
- [ ] Search bar should be above selected filter #168

### Configuration setup
- [x] Add lacking filters in different products in search service #141
  - [x] https://github.com/cyfronet-fid/eosc-search-service/issues/179
